// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorChatAPI
{
    public partial class BoxChat
    {
        public BoxChat()
        {
            Message = new HashSet<Message>();
        }

        public int BoxId { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }

        public virtual GroupChat GroupChat { get; set; }
        public virtual ICollection<Message> Message { get; set; }
    }
}