// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorChatAPI
{
    public partial class Message
    {
        public Message()
        {
            Reaction = new HashSet<Reaction>();
        }

        public int MessageId { get; set; }
        public int? MessageNumber { get; set; }
        public int? MessageBase { get; set; }
        public string Content { get; set; }
        public DateTime TimeSend { get; set; }
        public int? BoxId { get; set; }
        public int? AccountGroupId { get; set; }
        public int MessageType { get; set; }

        public virtual AccountGroup AccountGroup { get; set; }
        public virtual BoxChat Box { get; set; }
        public virtual TypeOfMessage MessageTypeNavigation { get; set; }
        public virtual ICollection<Reaction> Reaction { get; set; }
    }
}