// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorChatAPI
{
    public partial class Reaction
    {
        public int ReactId { get; set; }
        public int Count { get; set; }
        public int? MessageId { get; set; }
        public int? ReeactionNumer { get; set; }
        public int? TypeOfReactionId { get; set; }
        public int? AccountGroupId { get; set; }

        public virtual AccountGroup AccountGroup { get; set; }
        public virtual Message Message { get; set; }
        public virtual TypeOfReaction TypeOfReaction { get; set; }
    }
}