// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorChatAPI
{
    public partial class StatusInBoxChat
    {
        public int StatusId { get; set; }
        public int? AccountGroupId { get; set; }
        public int? TypeOfPermissionId { get; set; }
        public bool? IsCreator { get; set; }
        public string CurrentStatus { get; set; }

        public virtual AccountGroup AccountGroup { get; set; }
        public virtual TypeOfPermission TypeOfPermission { get; set; }
    }
}