// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorChatAPI
{
    public partial class TypeOfReaction
    {
        public TypeOfReaction()
        {
            Reaction = new HashSet<Reaction>();
        }

        public int TypeOfReactionId { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }

        public virtual ICollection<Reaction> Reaction { get; set; }
    }
}