// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorChatAPI
{
    public partial class TypeOfMessage
    {
        public TypeOfMessage()
        {
            Message = new HashSet<Message>();
        }

        public int TypeOfMessageId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }

        public virtual ICollection<Message> Message { get; set; }
    }
}